---
# tasks file for stackdeploy

- name: deploy stack from compose file 
  community.docker.docker_stack: 
    state: present
    name: mystack
    compose: 
      - /home/mohammed/docker-project/docker-compose.yaml